### ISSUE TITLE
Can I get the labels for the synced data?

### ISSUE THREAD

**Issue by Gary769581667** [SizheAn/MARS#2]
The GIF  on the README file is beautiful, but I find nowhere to reproduce this  GIF and  I can't  find the labels for .mat file data.
Could anyone give me some clues? Thanks so much.

**Comment by SizheAn** [comment]
Hi,

For reproduce the GIF, I wrote GUI in matlab but haven't upload it in the repository. It's very easy to visualize the data using scatter3 command in matlab or similar command in python, give it a try!

For the second question, inside the data folder, kinect_data_*.csv is the label file, radar_data_*.csv is the data file.

**Comment by SizheAn** [comment]
Soloved
